analysis.R---
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
---

## Loading and Setup
```{r, echo=FALSE}
source("analysis.R")

######### uncomment one line (data from one vis) ##############
vis <- "255charts"
# vis <- "boardofdirectors"
# vis <- "colleges"
# vis <- "anoncolleges"
# vis <- "exoplanets"
############################

data_original <- read.csv(paste("../data/",vis,"-participants.csv",sep=''))
data_visit_original <- read.csv(paste("../data/",vis,"-visits.csv",sep=''))
```

## Conversions and Filtering
```{r}
# per participant
data <- data_original %>%
  # convert time unit from ms to second
  mutate_at(vars(contains("time")), funs(./1000))

# set the minimum and maximum visit duration
MIN_DURATION <- 0.5
MAX_DURATION <- 100

data_visit <- data_visit_original %>% 
  # convert time unit from ms to second
  mutate(duration = duration/1000) %>% 
  # filter by visit duration
  filter(between(duration,MIN_DURATION,MAX_DURATION)) 

######### Groups ####
group_total <- data
# by condition
group_search_present <- group_total %>% filter(condition=='foresight')
group_no_search <- group_total %>% filter(condition=='control')
print(paste("Total:",length(group_total[,1]),"Search Present:",length(group_search_present[,1]),"No Search:",length(group_no_search[,1])))

# by the "used_search" factor
group_used_search <- group_total %>% filter(condition=='foresight' & used_search=='search')
group_used_search_and_no_search <- full_join(group_used_search,group_no_search)
print(paste("Total For Search Comparison:",length(group_used_search_and_no_search[,1]),"Search:",length(group_used_search[,1]),"Nonsearch:",length(group_no_search[,1])))

```


#Output
```{r}
# REPORT: % of participants attempting to locate specific data
proportionalTestCIPlot(group_total, x="strategy_locate",compareValue = "yes", group = "condition",yRange = c(0,1))
proportionalTest(data,"strategy_locate","yes","condition")

# REPORT: actively located items
fullReport(group_used_search_and_no_search, "strategy_active_search_num", "used_search", yRange=c(0,4), paired=FALSE)

# REPORT: exploration time
fullReport(group_used_search_and_no_search, "time_diff_exploration", "used_search",c(0,500))

# add the variable "avg visit time per chart" for each participant
group_add_mean_duration_between_group <- data_visit %>%
  group_by(postId, used_search, chart) %>% #aggregate visits by chart name
  summarise(duration=sum(duration)) %>%
  group_by(postId) %>%
  summarise(mean_duration=mean(duration)) %>%
  inner_join(group_used_search_and_no_search)

# REPORT: average visit time per chart
fullReport(group_add_mean_duration_between_group,"mean_duration","used_search", c(0,16))

group_add_mean_duration_within_group <- data_visit %>%
  filter(search_state!="non_search") %>% # first delete the visits from the "used search" group
  group_by( postId, used_search, search_state, chart) %>% #aggregate visits by chart name + search state
  summarise(duration=sum(duration)) %>%
  group_by( postId, search_state) %>%
  summarise(mean_duration=mean(duration)) %>%
  spread(search_state,mean_duration,fill=0) %>%
  filter(using_box>0) %>% # those who visited at least one chart during searching
  gather(search_state,mean_duration,using_box:not_using_box)

# REPORT: average visit time per chart - within group (during search or outside search)
fullReport(data=group_add_mean_duration_within_group,y="mean_duration",group="search_state", yRange=c(0,16), paired=TRUE)

```

