name: CI

on: 
  pull_request:
    branches:
    - master
  
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
    - name: test yarn
      with:
        node-version: '10.x'
    - run: yarn install
