name: CI

on: 
  pull_request:
    branches:
    - master

job:
  build:
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    - name: test-install
    - run: yarn install
